import { WeaponStats } from "@prisma/client";

export type StatsTableRecord = {
  id: bigint;
  name: string;
  winRatePercentage: number;
  gamesPlayed: number;
  gamesWon: number;
  gamesLost: number;
  gamesDrawn: number;
  kda: number;
  killsPerGame: number;
  deathsPerGame: number;
  assistsPerGame: number;
  damagePerRound: number;
  damagePerGame: number;
  headshotPercentage: number;
  kills: number;
  deaths: number;
  assists: number;
  headshots: number;
  roundsWon: number;
  totalRounds: number;
  headshotsPerGame: number;
  roundsWonPerGame: number;
  totalRoundsPerGame: number;
  roundsWinPercentage: number;
  damage: number;

  weapons?: WeaponStats[];
};

export type WeaponsTableRecord = {
  id: bigint;
  name: string;
  knifeDeaths: number;
  knifeKills: number;
  knifeKillsPerGame: number;
  zeusKills: number;
  zeusKillsPerGame: number;
  grenadeOrMolotovKills: number;
  grenadeOrMolotovKillsPerGame: number;
  glockKills: number;
  glockKillsPerGame: number;
  uspOrP2000Kills: number;
  uspOrP2000KillsPerGame: number;
  deagleKills: number;
  deagleKillsPerGame: number;
  otherPistolsKills: number;
  otherPistolsKillsPerGame: number;
  mac10OrMp9Kills: number;
  mac10OrMp9KillsPerGame: number;
  p90Kills: number;
  p90KillsPerGame: number;
  otherSMGKills: number;
  otherSMGKillsPerGame: number;
  shotgunKills: number;
  shotgunKillsPerGame: number;
  negevOrM249Kills: number;
  negevOrM249KillsPerGame: number;
  ak47Kills: number;
  ak47KillsPerGame: number;
  m4a4Kills: number;
  m4a4KillsPerGame: number;
  m4a1sKills: number;
  m4a1sKillsPerGame: number;
  awpKills: number;
  awpKillsPerGame: number;
  scoutKills: number;
  scoutKillsPerGame: number;
  famasKills: number;
  famasKillsPerGame: number;
  galilKills: number;
  galilKillsPerGame: number;
  autocampKills: number;
  autocampKillsPerGame: number;
  scopedRiflesKills: number;
  scopedRiflesKillsPerGame: number;
  otherKills: number;
  otherKillsPerGame: number;
};

export type Stats = {
  kills: number;
  deaths: number;
  assists: number;
  headshots: number;
  rounds_won: number;
  total_rounds: number;
  damage: number;
  match_outcome: "Win" | "Loss" | "Draw";
  name: string;
  knife_kills: number;
  knife_deaths: number;
  weapons: { [weaponName: string]: number };
};
