import { PlayerStats } from "@prisma/client";

export const NUMBER_OF_MATCHES_SEPARATOR = 8;
export const SEPARATOR_PLAYER = {
  id: 0,
  name: "//////////////////////////////////",
  winRatePercentage: null,
  gamesPlayed: null,
  gamesWon: null,
  gamesLost: null,
  gamesDrawn: null,
  kda: null,
  killsPerGame: null,
  deathsPerGame: null,
  assistsPerGame: null,
  damagePerRound: null,
  damagePerGame: null,
  headshotPercentage: null,
  kills: null,
  deaths: null,
  assists: null,
  headshots: null,
  roundsWon: null,
  totalRounds: null,
  headshotsPerGame: null,
  roundsWonPerGame: null,
  totalRoundsPerGame: null,
  roundsWinPercentage: null,
  damage: null,
  knifeKills: null,
  knifeDeaths: null,
  weapons: [],
} as unknown as PlayerStats;
